use std::path::{Path, PathBuf};

#[path = "registry_source.rs"]
mod registry_source;

/// Parse docs/FLAGS.md into the boot audit's registry (`env_audit.rs` includes the output).
///
/// Mirrors the flags census (`tools/check-flags.sh`): a `MEMRA_...` token ANYWHERE outside the
/// "Removed" ledgers documents a name (a trailing `*` documents a prefix family), because that
/// is what the census accepts today and the audit must not refuse a name the census passed.
/// Definitions are stricter: the first cell of a live table row (`| \`MEMRA_X\` | ...`).
/// A ledger is any heading, at any level, whose text starts with `Removed`; it ends at the next
/// heading of the same or a shallower level. Inside it, a definition block is a `- ` bullet or
/// a `| ` row together with its indented continuation lines, and EVERY non-prefix name in the
/// block is retired (ledgers delete several doors in one bullet), minus names that still have a
/// live DEFINITION (prose mentions in live rows do not un-retire a door). A retired name that a
/// prose wildcard would also cover stays retired: the audit checks the retired set first.
///
/// Prepared packages receive their complete source corpus through the shared receiver.
/// Without that provenance the legacy workspace/absent-docs behavior remains explicit.
pub(super) fn generate_env_registry(out: &Path) {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    generate_env_registry_for_manifest(out, &manifest);
}

/// The explicit manifest seam also lets the CPU integration exercise this caller
/// through Cargo without executing the engine's native compiler loop.
pub(super) fn generate_env_registry_for_manifest(out: &Path, manifest: &Path) {
    println!("cargo:rustc-check-cfg=cfg(memra_env_registry_present)");
    match registry_source::acquire(manifest, "memra-engine") {
        Ok(Some(prepared)) => {
            let (flags, sources) = prepared.text_inputs();
            let rendered = render_env_registry(flags, &sources);
            prepared
                .recheck()
                .expect("registry request changed before output");
            write_generated(out, "memra_env_registry.rs", rendered.as_bytes());
            let provenance =
                serde_json::to_vec(&prepared.provenance).expect("registry provenance JSON");
            write_generated(out, "memra_env_registry.provenance.json", &provenance);
            prepared
                .recheck()
                .expect("registry request changed during output");
            println!("cargo:rustc-cfg=memra_env_registry_present");
            return;
        }
        Ok(None) => {}
        Err(reason) => panic!("{reason}"),
    }
    if !registry_source::owns_workspace(manifest).expect("registry workspace ownership refused") {
        println!(
            "cargo:warning=env audit registry: no prepared provenance or canonical engine workspace owner; the MEMRA_* boot audit is inert in this binary"
        );
        write_empty_registry(out);
        return;
    }
    let flags = manifest.join("../../docs/FLAGS.md");
    println!("cargo:rerun-if-changed={}", flags.display());
    let text = match std::fs::read_to_string(&flags) {
        Ok(t) => t,
        Err(e) => {
            println!(
                "cargo:warning=env audit registry: {} not readable ({e}); packaged build, the \
                 MEMRA_* boot audit is inert in this binary",
                flags.display()
            );
            write_empty_registry(out);
            return;
        }
    };
    println!("cargo:rustc-cfg=memra_env_registry_present");
    let sources = workspace_rust_sources(manifest);
    let source_texts: Vec<&str> = sources.iter().map(String::as_str).collect();
    let src = render_env_registry(&text, &source_texts);
    std::fs::write(out.join("memra_env_registry.rs"), src).expect("write env registry");
}

fn write_empty_registry(out: &Path) {
    std::fs::write(
        out.join("memra_env_registry.rs"),
        "// generated by build.rs: docs/FLAGS.md absent, registry empty\n\
         pub const LEGAL_NAMES: &[&str] = &[];\n\
         pub const LEGAL_PREFIXES: &[&str] = &[];\n\
         pub const OWNED_FAMILIES: &[&str] = &[];\n\
         pub const RETIRED: &[(&str, &str)] = &[];\n",
    )
    .expect("write env registry");
}

fn write_generated(out: &Path, name: &str, bytes: &[u8]) {
    use std::io::Write;
    let temporary = out.join(format!(".{name}.{}.tmp", std::process::id()));
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temporary)
        .expect("create owned registry output temporary");
    let result = (|| {
        file.write_all(bytes)?;
        file.sync_all()?;
        std::fs::rename(&temporary, out.join(name))
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(&temporary);
    }
    result.expect("commit generated registry output");
}

fn workspace_rust_sources(manifest: &Path) -> Vec<String> {
    // Sources are scanned once per engine build (no rerun-if-changed on them: a sibling-crate
    // edit must not recompile the CUDA crate; the families move rarely and the FLAGS.md rerun
    // catches a catalog change).
    let mut sources = Vec::new();
    let mut roots = Vec::new();
    if let Ok(rd) = std::fs::read_dir(manifest.join("..")) {
        for entry in rd.flatten() {
            let src = entry.path().join("src");
            if src.is_dir() {
                roots.push(src);
            }
        }
    }
    roots.sort();
    for root in roots {
        let mut stack = vec![root];
        while let Some(dir) = stack.pop() {
            let Ok(rd) = std::fs::read_dir(&dir) else {
                continue;
            };
            for entry in rd.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|x| x == "rs") {
                    let Ok(text) = std::fs::read_to_string(&path) else {
                        continue;
                    };
                    sources.push(text);
                }
            }
        }
    }
    sources
}

/// Render the registry from immutable UTF-8 input text, without filesystem or environment reads.
/// Acquisition, source completeness and provenance are the caller's responsibility.
pub(super) fn render_env_registry(text: &str, rust_sources: &[&str]) -> String {
    fn tokens(cell: &str) -> Vec<(String, bool)> {
        let bytes = cell.as_bytes();
        let mut out = Vec::new();
        let mut i = 0;
        while let Some(rel) = cell[i..].find("MEMRA_") {
            let start = i + rel;
            let mut end = start;
            while end < bytes.len()
                && (bytes[end].is_ascii_uppercase()
                    || bytes[end].is_ascii_digit()
                    || bytes[end] == b'_')
            {
                end += 1;
            }
            let prefix = end < bytes.len() && bytes[end] == b'*';
            let stem = cell[start..end].trim_end_matches('_');
            if stem.len() > "MEMRA".len() {
                out.push((
                    if prefix {
                        format!("{stem}_")
                    } else {
                        stem.to_string()
                    },
                    prefix,
                ));
            }
            i = end.max(start + 1);
        }
        out
    }
    fn heading(line: &str) -> Option<(usize, &str)> {
        let level = line.bytes().take_while(|b| *b == b'#').count();
        if level == 0 || level > 6 || !line[level..].starts_with(' ') {
            return None;
        }
        Some((level, line[level..].trim()))
    }
    let mut defs = std::collections::BTreeSet::new();
    let mut legal = std::collections::BTreeSet::new();
    let mut prefixes = std::collections::BTreeSet::new();
    let mut ledger: std::collections::BTreeMap<String, String> = Default::default();
    let mut removed: Option<(usize, String)> = None; // (heading level, heading text)
    let mut in_block = false;
    for line in text.lines() {
        if let Some((level, text)) = heading(line) {
            in_block = false;
            removed = match &removed {
                Some((lvl, _)) if level > *lvl && !text.starts_with("Removed") => removed.clone(),
                _ if text.starts_with("Removed") => Some((level, text.to_string())),
                _ => None,
            };
            continue;
        }
        if let Some((_, h)) = &removed {
            // a bullet, a table row, or a line that opens with a backticked name (the lane-local
            // `### Removed experiments` ledger writes `\`MEMRA_X\`: removed before merge`)
            let starts =
                line.starts_with("- ") || line.starts_with("| ") || line.starts_with("`MEMRA_");
            let continues = in_block && line.starts_with(' ') && !line.trim().is_empty();
            if starts || continues {
                in_block = true;
                for (name, prefix) in tokens(line) {
                    if !prefix {
                        ledger.entry(name).or_insert_with(|| h.clone());
                    }
                }
            } else {
                in_block = false;
            }
            continue;
        }
        for (name, prefix) in tokens(line) {
            if prefix {
                prefixes.insert(name);
            } else {
                legal.insert(name);
            }
        }
        if let Some(rest) = line.strip_prefix("| ") {
            let mut cells = rest.split('|');
            let first_cell = cells.next().unwrap_or("");
            // A live row whose default cell opens with REMOVED documents a door that is gone
            // (`| \`MEMRA_SEL_DOWN8\` | **REMOVED 2026-08-29** | ...`): the name stays documented
            // for the census, and retired for the audit, with the row as its ledger.
            let second_cell = cells.next().unwrap_or("").trim().trim_start_matches('*');
            let removed_row = second_cell.starts_with("REMOVED");
            for (name, prefix) in tokens(first_cell) {
                if prefix {
                    continue;
                }
                if removed_row {
                    ledger.entry(name).or_insert_with(|| {
                        format!("row marked {}", second_cell.trim_end_matches('*'))
                    });
                } else {
                    defs.insert(name);
                }
            }
        }
    }
    // Owned families come from the code, not from the catalog: a `MEMRA_<FAMILY>_` prefix that
    // any crate in the workspace READS under three or more distinct names (every `crates/*/src`,
    // the census's discovery rule; memra-kv, memra-gguf, memra-lanes and memra-tokenizer all read
    // doors). The catalog also documents shell-side knobs (`MEMRA_CI_*`, `MEMRA_GATE_*`, ...) that
    // no Rust reads, and a typo among those is the launcher's business, not a boot refusal.
    let mut read_names = std::collections::BTreeSet::new();
    for text in rust_sources {
        for line in text.lines() {
            if !(line.contains("env::var") || line.contains("env!(")) {
                continue;
            }
            for (name, prefix) in tokens(line) {
                if !prefix {
                    read_names.insert(name);
                }
            }
        }
    }
    let mut family_counts: std::collections::BTreeMap<String, usize> = Default::default();
    for n in &read_names {
        if let Some(rest) = n.strip_prefix("MEMRA_")
            && let Some(cut) = rest.find('_')
        {
            *family_counts
                .entry(n[..("MEMRA_".len() + cut + 1)].to_string())
                .or_default() += 1;
        }
    }
    let owned: Vec<String> = family_counts
        .into_iter()
        .filter(|(_, c)| *c >= 3)
        .map(|(f, _)| f)
        .collect();
    assert!(
        owned.len() > 5,
        "env audit registry: only {} owned families derived from source",
        owned.len()
    );
    let retired: Vec<(String, String)> = ledger
        .into_iter()
        .filter(|(n, _)| !defs.contains(n))
        .collect();
    for (n, _) in &retired {
        legal.remove(n);
    }
    assert!(
        legal.len() > 200,
        "env audit registry: only {} legal names parsed from FLAGS.md",
        legal.len()
    );
    assert!(
        !retired.is_empty(),
        "env audit registry: no retired doors parsed from FLAGS.md"
    );
    let mut src = String::new();
    src.push_str("// generated by build.rs from docs/FLAGS.md; do not edit\n");
    src.push_str("pub const LEGAL_NAMES: &[&str] = &[\n");
    for n in &legal {
        src.push_str(&format!("    {n:?},\n"));
    }
    src.push_str("];\npub const LEGAL_PREFIXES: &[&str] = &[\n");
    for p in &prefixes {
        src.push_str(&format!("    {p:?},\n"));
    }
    src.push_str("];\npub const OWNED_FAMILIES: &[&str] = &[\n");
    for f in &owned {
        src.push_str(&format!("    {f:?},\n"));
    }
    src.push_str("];\npub const RETIRED: &[(&str, &str)] = &[\n");
    for (n, h) in &retired {
        src.push_str(&format!("    ({n:?}, {h:?}),\n"));
    }
    src.push_str("];\n");
    src
}
