#!/usr/bin/env python3
"""One cell of the step37 spec sweep: three vendor-default sampled decode reps plus one
engagement probe. Prints one summary line to stdout.

VENDOR-DEFAULT SAMPLED means a request with NO sampling params at all; the server applies the
model's published defaults. We never serve greedy, so that is the only shape a serving number
may be quoted from.

THINKING MODEL: at these caps message.content is EMPTY and every generated byte arrives in
message.reasoning. Both are counted and hashed, and an empty completion is rejected IN the
instrument, because sha256("") equals itself and two empty results would compare EQUAL and
report a false PASS. That defect already produced a false 12/12 MATCH in this lane.

ENGAGEMENT comes from `usage.spec` in the RESPONSE BODY, not from a log grep: a counter in
this lane printed the same value with spec off and proved nothing. It is read in BOTH
directions, so a spec arm with no rounds is reported as NOT ENGAGED rather than quoted.
"""
import hashlib
import json
import os
import statistics
import time
import urllib.request

port = os.environ["P"]
arm = os.environ["ARM"]
rnd = os.environ["RND"]
URL = "http://127.0.0.1:%s/v1/chat/completions" % port


def post(payload, timeout=1800):
    return urllib.request.urlopen(
        urllib.request.Request(
            URL, data=json.dumps(payload).encode(), headers={"Content-Type": "application/json"}
        ),
        timeout=timeout,
    )


def stream_rep():
    d = json.load(open("/root/curve-0400.json"))
    d["stream"] = True
    d["max_tokens"] = 400
    t0 = time.perf_counter()
    first = None
    n = 0
    body = []
    try:
        r = post(d)
        while True:
            line = r.readline()
            if not line:
                break
            s = line.decode("utf-8", "replace").strip()
            if s.startswith("data:") and "[DONE]" not in s:
                try:
                    j = json.loads(s[5:].strip())
                except Exception:
                    continue
                dd = (j.get("choices") or [{}])[0].get("delta") or {}
                piece = (dd.get("reasoning") or "") + (dd.get("content") or "")
                if piece:
                    if first is None:
                        first = time.perf_counter() - t0
                    n += 1
                    body.append(piece)
        r.close()
        total = time.perf_counter() - t0
    except Exception as e:
        return None, "EXC:" + type(e).__name__
    text = "".join(body)
    if not text.strip():
        return None, "EMPTY"
    if first is None or n < 2:
        return None, "NOROWS"
    # Greedy-loop-shaped output is a known artifact, never a finding and never a perf row.
    # Vendor-default sampling should not produce it; flagged, never silently dropped.
    words = text.split()
    note = ""
    if len(words) > 40:
        tail = words[-40:]
        if len({" ".join(tail[i:i + 3]) for i in range(len(tail) - 2)}) <= 6:
            note = "LOOP"
    return (n - 1) / (total - first), note


def engagement():
    """Non-streaming probe: usage.spec straight out of the response body."""
    d = json.load(open("/root/curve-0400.json"))
    d["stream"] = False
    d["max_tokens"] = 120
    try:
        r = post(d)
        j = json.loads(r.read().decode())
        r.close()
    except Exception as e:
        return "usage=EXC:" + type(e).__name__, ""
    m = (j.get("choices") or [{}])[0].get("message") or {}
    text = (m.get("reasoning") or "") + (m.get("content") or "")
    usage = j.get("usage") or {}
    spec = usage.get("spec")
    sha = hashlib.sha256(text.encode()).hexdigest()[:16] if text.strip() else "EMPTY-INVALID"
    if spec is None:
        return "spec_usage=ABSENT", sha
    # worker::SpecUsage is {rounds, drafted, accepted}. It has appeared both FLAT and keyed by
    # model name across surfaces, so normalise BOTH into one "rounds=..." spelling: the
    # engagement audit keys on that string, and a shape it cannot parse would read as ABSENT,
    # i.e. it would silently call an engaged arm unproven.
    def fmt(prefix, c):
        return "%srounds=%s,drafted=%s,accepted=%s" % (
            prefix, c.get("rounds"), c.get("drafted"), c.get("accepted"))
    if isinstance(spec, dict) and "rounds" in spec:
        return "spec_usage=" + fmt("", spec), sha
    parts = []
    for model, c in (spec.items() if isinstance(spec, dict) else []):
        if isinstance(c, dict) and "rounds" in c:
            parts.append(fmt(model + ":", c))
    if not parts:
        return "spec_usage=UNPARSED:" + json.dumps(spec)[:120], sha
    return "spec_usage=" + ";".join(parts), sha


tp = []
notes = []
for _ in range(3):
    v, note = stream_rep()
    if note:
        notes.append(note)
    if v is not None and note != "LOOP":
        tp.append(v)
eng, sha = engagement()
head = "rnd=%s arm=%-6s" % (rnd, arm)
if tp:
    print("%s tok/s_med=%.2f rows=%d %s sha=%s notes=%s"
          % (head, statistics.median(tp), len(tp), eng, sha, notes or "none"))
else:
    print("%s NO VALID ROWS - INVALID %s notes=%s" % (head, eng, notes))
