#!/usr/bin/env python3
"""One arm of the W8_VIEW first-token gate. Writes one JSON line to stdout.

GREEDY, max_tokens=1, four REAL prompts: one forward, no cascade possible, so a difference is
the door itself and not tie-break drift. A 128-token greedy tape is taken alongside, reported
separately because full-generation divergence on a numeric-class door is ordinary cascade and
is never the gate result.

THINKING MODEL: at these caps message.content is EMPTY and every generated byte arrives in
message.reasoning, so both are hashed. Empty completions are rejected IN the instrument:
sha256("") is a constant, so two empty results compare EQUAL and a naive gate reports a false
PASS. That defect already produced a false 12/12 MATCH in this lane.
"""
import hashlib
import json
import os
import sys
import urllib.request

port = os.environ["P"]
arm = os.environ["ARM"]


def prompts():
    for n in ("curve-0128", "curve-0400", "curve-1000"):
        yield n, json.load(open("/root/%s.json" % n))
    d = json.load(open("/root/curve-0400.json"))
    d = dict(d)
    d["messages"] = [{"role": "user", "content": json.load(open("/root/agentic8.json"))[0]}]
    yield "agentic8", d


out = {}
for name, base in prompts():
    for cap, tag in ((1, "first"), (128, "tape")):
        d = dict(base)
        d["stream"] = False
        d["temperature"] = 0.0
        d["max_tokens"] = cap
        body = ""
        try:
            r = urllib.request.urlopen(
                urllib.request.Request(
                    "http://127.0.0.1:%s/v1/chat/completions" % port,
                    data=json.dumps(d).encode(),
                    headers={"Content-Type": "application/json"},
                ),
                timeout=1800,
            )
            j = json.loads(r.read().decode())
            r.close()
            m = (j.get("choices") or [{}])[0].get("message") or {}
            body = (m.get("reasoning") or "") + (m.get("content") or "")
        except Exception as e:
            print("EXC %s/%s %s" % (name, tag, type(e).__name__), file=sys.stderr)
        key = "%s/%s" % (name, tag)
        out[key] = ["EMPTY-INVALID", 0] if not body.strip() else [
            hashlib.sha256(body.encode()).hexdigest()[:16],
            len(body),
        ]
print(json.dumps({"arm": arm, "cells": out}))
