[package]
name="memra-lifecycle-http-cpu"
version="0.0.0"
edition="2024"

[workspace]

[dependencies]
axum = { version = "=0.7.9" }
async-stream = { version = "=0.3.6" }
futures-core = { version = "=0.3.32" }
tokio = { version = "=1.52.3", features = ["rt-multi-thread", "macros", "net", "sync", "time", "signal", "io-util"] }
serde_json = { version = "=1.0.150", features = ["preserve_order"] }
tower = { version = "=0.5.3", features = ["util"] }
