#!/usr/bin/env python3
"""Convert own session corpus -> SpecForge {id, conversations} JSONL (prompts only).
Assistant responses are NOT copied — they get regenerated by the target model
(scripts/regenerate_train_data.py), so no transcript content leaks into training labels.
Dedup + length-filtered; deterministic order for resumable regen."""
import argparse, hashlib, json, re
from pathlib import Path

SKIP_PAT = re.compile(
    r"<system-reminder>|<task-notification>|tool_result|<local-command|Caveat: The messages below|"
    r"^\s*\[Request interrupted", re.IGNORECASE)


def user_turns(f: Path):
    try:
        for line in f.open(errors="ignore"):
            try:
                d = json.loads(line)
            except Exception:
                continue
            if d.get("type") != "user":
                continue
            c = (d.get("message") or {}).get("content")
            texts = [c] if isinstance(c, str) else \
                [b.get("text", "") for b in c if isinstance(b, dict) and b.get("type") == "text"] if isinstance(c, list) else []
            for t in texts:
                t = t.strip()
                if 80 <= len(t) <= 8000 and not SKIP_PAT.search(t):
                    yield t
    except Exception:
        return


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus-root", type=Path, default=Path("/scratch/corpus/sessions"))
    ap.add_argument("--tiers", nargs="+", default=["claude", "codex", "eigen", "hermes"])
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--max-per-tier", type=int, default=200_000)
    args = ap.parse_args()

    seen, n_out = set(), 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w") as out:
        for tier in args.tiers:
            n_tier = 0
            for f in sorted((args.corpus_root / tier).rglob("*.jsonl")):
                for t in user_turns(f):
                    h = hashlib.sha256(t.encode()).hexdigest()[:16]
                    if h in seen:
                        continue
                    seen.add(h)
                    out.write(json.dumps({
                        "id": f"own-{tier}-{h}",
                        "conversations": [{"role": "user", "content": t}],
                    }) + "\n")
                    n_out += 1
                    n_tier += 1
                    if n_tier >= args.max_per_tier:
                        break
                if n_tier >= args.max_per_tier:
                    break
            print(f"{tier}: {n_tier}")
    print(f"total unique prompts: {n_out} -> {args.out}")


if __name__ == "__main__":
    main()
