#!/bin/bash
# tpwalk16/17 f32-indexer instrument posture; explicit core doors and graph preconditions.
export MEMRA_GLM5_TP=all@0,1
export MEMRA_TP_TRANSPORT=device-push
export MEMRA_GLM5_TP_EXPERT_SPLIT=1 MEMRA_TP_AR_1STAGE=1
export MEMRA_GLM5_TP_SYMMETRIC=1 MEMRA_GLM5_TP_SYM_GRAPH=1 MEMRA_GLM5_TP_SYM_GRAPH_MLA=1
export MEMRA_MLA_SEG_WS=1 MEMRA_HTOD_DIET=1 MEMRA_MOE_VROWS_DEV_TABLES=1
export MEMRA_GLM5_Q8_FUSE=1 MEMRA_GLM5_W8=1 MEMRA_KDA_FUSED_PROJ=1
export MEMRA_B200_MATVEC_ARM=1 MEMRA_B200_GEMV_V2=1 MEMRA_B200_PRIME_V2=1
export MEMRA_B200_DSA_DECODE=2 MEMRA_B200_DSA_SELECT=1 MEMRA_DSA_SCORE_RP=1
export MEMRA_MLA_COALESCE=1 MEMRA_MLA_TC_PREFILL=1
export MEMRA_MOE_HOST_PINNED=0 MEMRA_MOE_RESIDENT_GB=124
export MEMRA_GLM5_TP_SPLIT_GROUPED_PRIME=1 MEMRA_GLM5_TP_SPLIT_PRIME_HOSTDIET=1
export MEMRA_SERVE_SPEC=0 MEMRA_HYPER_BATCH=0 MEMRA_GLM53_NVFP4_LATENT=0
export MEMRA_HC_FUSED_PRE=0 MEMRA_HC_DECODE_WS=0 MEMRA_MLA_DECODE_SPLIT=0
export BOXP_MODE=timed BOXP_MAX_NEW=160 BOXP_LOGIT_STEPS=0
export MEMRA_DSA_SCORE_TC=0

# Match the served loader: gather in memory rather than materializing a second disk copy.
export MEMRA_ST_REPACK_DISK=0
