#!/usr/bin/env python3
"""262k-context receipt cell (owner-priority add-on to the prefix-latent box window).

Question it answers with a receipt, not arithmetic: is the 2-card serving shape
(MEMRA_PP_SPLITS=24, cards 0/1) a 262,144-context product? The arithmetic says the
context-sized latent planes cost a few GiB of moe-cache residency per deep session;
this cell measures what the residency actually settles at and what a deep prime
actually costs through the serving surface.

Run against a server booted with MEMRA_CTX=262144 on the same 2-card shape (prefix
cache OFF, MEMRA_PREFIX_CACHE_MB=0, so the residency receipt is not confounded by
entry bytes). The script:

  1. records per-card VRAM (nvidia-smi) at READY, before any session;
  2. opens session 1: a SHORT real prompt (pool p5), then records VRAM;
  3. opens session 2: the DEEP prompt, ~30-60k tokens of REAL text (repo docs +
     the agent pool, deduplicated reading order, never synthetic filler), streamed
     through /v1/completions so TTFD = wall clock to the first generated byte and
     prefill tok/s = prompt_tokens / TTFD; then records VRAM again;
  4. banks the server log tail (moe-cache residency lines; NOTE the known gap:
     moe_cache_stats is not wired through PP stage engines, so per-card staging
     counters come from nvidia-smi deltas + whatever the log prints, named as such).

TTFD here is a timing row: touch /root/TIMING-IN-FLIGHT before running and remove it
after (co-tenant protocol).

usage: ctx262k-cell.py <outdir> [deep_target_tokens]
env:   EP (default http://127.0.0.1:18400), MODEL (default zai/glm-5.3-flash),
       PROMPTS_JSON, DOCS_DIR (default /root/memra/docs)
"""

import glob
import json
import os
import subprocess
import sys
import time
import urllib.request

OUT = sys.argv[1]
DEEP_TARGET = int(sys.argv[2]) if len(sys.argv) > 2 else 45_000
EP = os.environ.get("EP", "http://127.0.0.1:18400")
MODEL = os.environ.get("MODEL", "zai/glm-5.3-flash")
POOL = json.load(open(os.environ.get("PROMPTS_JSON", "/root/memra/research/glm53-flash-bringup-20260827/decode-attribution-receipts/prompts.json")))["decode"]
DOCS_DIR = os.environ.get("DOCS_DIR", "/root/memra/docs")
os.makedirs(OUT, exist_ok=True)
RESULTS = {"ep": EP, "model": MODEL, "deep_target_tokens": DEEP_TARGET, "vram": {}, "rows": []}


def vram(label):
    out = subprocess.run(
        ["nvidia-smi", "--query-gpu=index,memory.used,memory.total", "--format=csv,noheader"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    RESULTS["vram"][label] = out.splitlines()
    print(f"  [vram @ {label}]")
    for line in out.splitlines():
        print(f"    {line}")


def completion_streamed(prompt, name, max_tokens=32):
    """Raw /v1/completions, streamed; TTFD = first content byte. Sampled shape is not the
    point here (this is a prefill-cost receipt); greedy keeps the row deterministic."""
    body = {
        "model": MODEL,
        "prompt": prompt,
        "max_tokens": max_tokens,
        "stream": True,
        "temperature": 0.0,
        "stream_options": {"include_usage": True},
    }
    req = urllib.request.Request(
        EP + "/v1/completions",
        data=json.dumps(body).encode(),
        headers={"content-type": "application/json"},
    )
    ttfd, usage, chunks, err = None, None, [], None
    t0 = time.time()
    try:
        with urllib.request.urlopen(req, timeout=3600) as r:
            for rl in r:
                s = rl.decode().strip()
                if not s.startswith("data:"):
                    continue
                pay = s[5:].strip()
                if pay == "[DONE]":
                    break
                o = json.loads(pay)
                if o.get("usage"):
                    usage = o["usage"]
                c = (o.get("choices") or [{}])[0]
                if c.get("text"):
                    if ttfd is None:
                        ttfd = round(time.time() - t0, 3)
                    chunks.append(c["text"])
    except Exception as e:  # noqa: BLE001 - the failure is the receipt
        err = f"{type(e).__name__}: {e}"
    u = usage or {}
    row = {
        "name": name,
        "ttfd_s": ttfd,
        "wall_s": round(time.time() - t0, 3),
        "prompt_tokens": u.get("prompt_tokens"),
        "completion_tokens": u.get("completion_tokens"),
        "prefill_tok_s": (
            round(u["prompt_tokens"] / ttfd, 1) if ttfd and u.get("prompt_tokens") else None
        ),
        "error": err,
    }
    open(f"{OUT}/{name}.json", "w").write(json.dumps({"row": row, "text": "".join(chunks)}, indent=1))
    RESULTS["rows"].append(row)
    return row


def build_deep_prompt(target_tokens):
    """~4 chars/token planning figure; real text only: every .md under DOCS_DIR in sorted
    order (each file once), then the agent pool, then research docs if still short."""
    parts, sources = [], []
    for path in sorted(glob.glob(f"{DOCS_DIR}/*.md")) + sorted(
        glob.glob("/root/memra/research/glm53-flash-bringup-20260827/*.md")
    ):
        try:
            parts.append(open(path, errors="replace").read())
            sources.append(path)
        except OSError:
            continue
        if sum(len(p) for p in parts) >= target_tokens * 4:
            break
    if sum(len(p) for p in parts) < target_tokens * 4:
        parts.extend(p["text"] for p in POOL)
        sources.append("agent-pool")
    doc = "\n\n".join(parts)[: target_tokens * 4]
    RESULTS["deep_sources"] = sources
    return (
        "You are reviewing the following engineering documentation corpus.\n\n"
        + doc
        + "\n\nIn one sentence, name the single riskiest assumption in this corpus."
    )


print("### 262k cell: per-card VRAM at READY (before any session)")
vram("ready")

print("### session 1: short real prompt (pool p5)")
completion_streamed(POOL[5]["text"], "s1-short", max_tokens=32)
vram("after-session-1")

print(f"### session 2: DEEP prompt (~{DEEP_TARGET} tokens of real text) — TIMED ROW")
deep = build_deep_prompt(DEEP_TARGET)
row = completion_streamed(deep, "s2-deep", max_tokens=32)
print(
    f"  deep: prompt_tokens={row['prompt_tokens']} TTFD={row['ttfd_s']}s "
    f"prefill={row['prefill_tok_s']} tok/s err={row['error']}"
)
vram("after-session-2")

open(f"{OUT}/ctx262k.json", "w").write(json.dumps(RESULTS, indent=1))
print("### banked", f"{OUT}/ctx262k.json")
if row["error"] or not row["ttfd_s"]:
    print("### DEEP PRIME DID NOT COMPLETE — the receipt is the refusal/error above")
    sys.exit(2)
