FROM python:3.12-slim-bookworm@sha256:8a7e7cc04fd3e2bd787f7f24e22d5d119aa590d429b50c95dfe12b3abe52f48b

COPY math-score-requirements.lock.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --require-hashes -r /tmp/requirements.txt \
    && rm /tmp/requirements.txt

COPY score_hourish_math.py /usr/local/bin/score-hourish-math
RUN chmod 0555 /usr/local/bin/score-hourish-math

ENTRYPOINT ["python3", "-I", "/usr/local/bin/score-hourish-math"]
