FROM python:3.12-slim-bookworm@sha256:8a7e7cc04fd3e2bd787f7f24e22d5d119aa590d429b50c95dfe12b3abe52f48b

COPY score_hourish_code.py /usr/local/bin/score-hourish-code
RUN chmod 0555 /usr/local/bin/score-hourish-code

ENTRYPOINT ["python3", "-I", "/usr/local/bin/score-hourish-code"]
