# lane/gemm-suffix driver.
#
# The question: can a CONTINUATION (suffix) prime ride the batched GEMM path, and does it stay
# the SAME numeric program as a cold full prime of the same bytes?
#
# LEG S -- SUFFIX BYTE IDENTITY, swept over suffix length. For each target suffix length L:
#   (1) establish a session with turn 1 (parks a cache),
#   (2) send turn 2 on the SAME session_id -> the worker rewinds and primes an L-token suffix,
#   (3) send the SAME BYTES on a FRESH session_id -> a cold full prime of the identical prompt.
# Greedy, so (2) and (3) must agree byte for byte. The sweep BRACKETS the 512-row SWA window
# (below it is where the chunk-local seq_end dropped the window mask) and reaches past the
# 4096-token chunk width, so a suffix that itself chunks into 4096 + short-tail is covered.
#
# LEG G -- TTFT on a GROWING conversation, 5 interleaved cold/warm pairs (the shape the affinity
# lane measured at ratio 1.012x). Pre-baked assistant text: both arms prime identical bytes.
#
# LEG F -- one FRESH prompt sized to 4096 + k, k in [16, 512): the shape in which the chunk-local
# seq_end was already wrong before any continuation existed. Its sha is reported for cross-arm
# comparison (default vs the MEMRA_STEP35_PRIME_BATCH_TSEND canary).
#
# INSTRUMENT RULES paid for in this lane:
#  * every generated byte of a thinking model is in `reasoning`; hash reasoning + content.
#  * sha256("") is a constant, so two empty completions compare EQUAL -> empties are rejected
#    HERE, and a row with no ttft or an HTTP error is not a row.
#  * a cold row that REWOUND is not a cold row; it is reported INVALID rather than compared.
import json, hashlib, os, time, urllib.request, urllib.error

port = os.environ["P"]; name = os.environ["NAME"]; logp = os.environ["LOG"]
MAXTOK = int(os.environ.get("MAXTOK", "256"))
URL = "http://127.0.0.1:%s/v1/chat/completions" % port
base = json.load(open("/root/curve-1000.json"))
U1 = base["messages"][0]["content"]

# Attempt-2 seams for the walk-only arm, all unset for the three battery-1 arms.
# WHY: the server's first-token deadline is a hard platform cap (TIMEOUT_MS_MAX = 90_000,
# crates/memra-server/src/main.rs) and the full-prompt WALK prime measured ~57.5 ms/token in
# attempt 1, so any cold walk prime past ~1500 tokens can never answer inside the deadline.
# GS_U1_WORDS truncates turn 1 to fit; the m-fork between the warm prefix's prime and the
# cold twin's prime is preserved at the smaller geometry.
_u1w = os.environ.get("GS_U1_WORDS", "").strip()
if _u1w:
    U1 = " ".join(U1.split()[:int(_u1w)])
# GS_LEGS=S skips LEG F and LEG G: at walk-everything speed LEG F (4096+k) and the deeper
# LEG G turns are unreachable inside the deadline, and the attribution question is LEG S's.
SKIP_FG = os.environ.get("GS_LEGS", "").strip().upper() == "S"
# GS_CAL_PAD shrinks the calibration pad so the second probe also fits the deadline.
CAL_PAD = int(os.environ.get("GS_CAL_PAD", "600"))

ABAKE = ("Here is the digested summary you asked for. The run covered trajectory optimization "
         "with iLQR, DDP and MPC, ran the nightly learning loop end to end, and recorded the "
         "per-stage timings alongside the convergence traces. The main takeaway is that the "
         "line-search schedule dominates wall time on this workload. ")
ASHORT = "Recorded. The line-search schedule dominates wall time here."
FILLER = ("alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi omicron "
          "pi rho sigma tau upsilon phi chi psi omega ").split()

def filler(nwords):
    if nwords <= 0: return ""
    reps = nwords // len(FILLER) + 1
    return " " + " ".join((FILLER * reps)[:nwords])

def turn1(nonce=""):
    return [{"role": "user", "content": nonce + U1}]

def turn2(asst, nwords, nonce=""):
    return turn1(nonce) + [
        {"role": "assistant", "content": asst},
        {"role": "user", "content": "Expand the second point and explain the trade-offs."
                                    + filler(nwords)}]

FIRST_KEYS = []
def stream_once(msgs, sid, maxtok=None):
    payload = {"model": "step37", "messages": msgs, "stream": True,
               "max_tokens": maxtok or MAXTOK, "temperature": 0}
    if sid: payload["session_id"] = sid
    req = urllib.request.Request(URL, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"})
    t0 = time.perf_counter(); ttft = None; parts = []
    try:
        r = urllib.request.urlopen(req, timeout=1800)
    except urllib.error.HTTPError as e:
        return (None, time.perf_counter() - t0, "", e.read().decode("utf-8", "replace")[:300])
    for raw in r:
        line = raw.decode("utf-8", "replace").strip()
        if not line.startswith("data:"): continue
        s = line[5:].strip()
        if s == "[DONE]": break
        try: ch = json.loads(s)
        except Exception: continue
        d = ch.get("choices", [{}])[0].get("delta", {}) or {}
        if d and not FIRST_KEYS: FIRST_KEYS.append(sorted(d.keys()))
        piece = (d.get("reasoning") or "") + (d.get("content") or "")
        if piece:
            if ttft is None: ttft = time.perf_counter() - t0
            parts.append(piece)
    return (ttft, time.perf_counter() - t0, "".join(parts), None)

PROBE = [0]
def prompt_tokens(msgs):
    """Exact prompt length read off the ENGINE's own prime receipt: every [gemm-prime] line
    carries seq_end = the request's absolute end position, which for a fresh prime IS the
    prompt token count. Measured, not estimated, and it does not depend on a usage block."""
    PROBE[0] += 1
    pos = logf.tell()
    stream_once(msgs, "gsPROBE-%s-%d" % (name, PROBE[0]), maxtok=1)
    logf.seek(pos); sl = logf.read(); logf.seek(0, 2)
    ends = []
    for l in sl.splitlines():
        if "[gemm-prime]" in l:
            for tok in l.split():
                if tok.startswith("seq_end="):
                    ends.append(int(tok[8:]))
    return max(ends) if ends else None

logf = open(logp, "r", errors="replace"); logf.seek(0, 2)
rows = []

def send(tag, key, msgs, sid):
    pos = logf.tell()
    ttft, total, text, err = stream_once(msgs, sid)
    logf.seek(pos); sl = logf.read(); logf.seek(0, 2)
    rewound = "plain-affinity: rewound to" in sl
    refused = ("plain-affinity resume failed" in sl) or ("affinity rewind failed" in sl)
    eng = [l for l in sl.splitlines() if "[gemm-prime] ENGAGED" in l]
    walk = [l for l in sl.splitlines() if "[gemm-prime] WALK" in l]
    def bases(lines):
        out = []
        for l in lines:
            for tok in l.split():
                if tok.startswith("base="):
                    out.append(int(tok[5:]))
        return out
    eb, wb = bases(eng), bases(walk)
    suffix_tokens = None
    for l in sl.splitlines():
        if "plain-affinity: rewound to" in l:
            p = l.split("(priming ")
            if len(p) > 1: suffix_tokens = int(p[1].split()[0])
    sha = hashlib.sha256(text.encode()).hexdigest()[:16] if text.strip() else None
    r = dict(tag=tag, key=key, ttft=ttft, total=total, chars=len(text), sha=sha,
             rewound=rewound, refused=refused, err=err, suffix=suffix_tokens,
             eng_fresh=sum(1 for b in eb if b == 0), eng_suffix=sum(1 for b in eb if b > 0),
             walk_fresh=sum(1 for b in wb if b == 0), walk_suffix=sum(1 for b in wb if b > 0))
    rows.append(r)
    print("    %-10s %-14s ttft=%s chars=%d sha=%s rewound=%s suffix=%s "
          "eng[fresh=%d suffix=%d] walk[fresh=%d suffix=%d]%s"
          % (tag, key, ("%.3f" % ttft) if ttft is not None else "NONE", len(text),
             sha or "EMPTY", rewound, suffix_tokens, r["eng_fresh"], r["eng_suffix"],
             r["walk_fresh"], r["walk_suffix"], (" err=%s" % err) if err else ""))
    for l in (eng + walk)[:2]:
        print("        %s" % l.strip()[:150])
    return r

# ---------------- calibration: words -> tokens, off the server's own tokenizer -------------
print("    --- CALIBRATION (server usage block) ---")
t_base = prompt_tokens(turn2(ASHORT, 0, nonce="[cal a] "))
t_pad = prompt_tokens(turn2(ASHORT, CAL_PAD, nonce="[cal b] "))
tpw = None
if t_base and t_pad and t_pad > t_base:
    tpw = (t_pad - t_base) / float(CAL_PAD)
print("    turn2(short,0)=%s turn2(short,600)=%s tokens_per_filler_word=%s"
      % (t_base, t_pad, ("%.4f" % tpw) if tpw else "UNKNOWN"))

def words_for(target_suffix, asst):
    """filler words so the SUFFIX (assistant text + follow-up user turn) is ~target tokens."""
    if not tpw: return max(0, int(target_suffix * 0.75))
    fixed = len(asst.split()) * 1.35 + 25          # assistant text + chat-template markers
    return max(0, int(round((target_suffix - fixed) / tpw)))

# ---------------- LEG S: suffix byte identity, swept ----------------
print("    --- LEG S: suffix byte identity (rewound suffix prime vs cold full prime) ---")
SWEEP = [("s0030", 30, ASHORT), ("s0250", 250, ABAKE), ("s0450", 450, ABAKE),
         ("s0700", 700, ABAKE), ("s1200", 1200, ABAKE), ("s4400", 4400, ABAKE)]
# GS_SWEEP trims the sweep for arms that only need a couple of points (the walk-only
# diagnostic pays 5.8 ms/token on BOTH sides, so the full sweep would hold the shared GPU lock
# for no extra signal). Unset = the full sweep, so the three battery-1 arms are unaffected.
_only = os.environ.get("GS_SWEEP", "").strip()
if _only:
    keep = set(_only.split(","))
    SWEEP = [row for row in SWEEP if row[0] in keep]
    print("    SWEEP TRIMMED to %s" % ",".join(k for k, _, _ in SWEEP))
ident = []
for key, target, asst in SWEEP:
    nw = words_for(target, asst)
    msgs2 = turn2(asst, nw, nonce="[leg-s %s] " % key)
    sid = "gsS-%s-%s" % (name, key)
    send("s-est", key, turn1(nonce="[leg-s %s] " % key), sid)
    w = send("s-warm", key, msgs2, sid)
    c = send("s-cold", key, msgs2, "gsSC-%s-%s" % (name, key))
    ident.append((key, target, nw, w, c))

# ---------------- LEG F: fresh 4096 + k, k in [16, 512) ----------------
print("    --- LEG F: FRESH prompt at 4096 + k (short trailing chunk, no continuation) ---")
legf = None
if SKIP_FG:
    print("    LEG F SKIPPED (GS_LEGS=S): a 4346-token walk prime cannot answer inside the "
          "90 s first-token deadline")
if tpw and not SKIP_FG:
    t0 = prompt_tokens(turn1(nonce="[leg-f probe] "))
    if t0:
        want = 4096 + 250
        nw = int(round((want - t0 - 6) / tpw))
        m = turn1(nonce="[leg-f] ") 
        m[0]["content"] = m[0]["content"] + filler(nw)
        got = prompt_tokens(m)
        print("    leg-F base=%s filler_words=%s measured_prompt_tokens=%s (target %d)"
              % (t0, nw, got, want))
        legf = send("f-fresh", "f4096k", m, None)
        legf = dict(legf, prompt_tokens=got)

# ---------------- LEG G: growing conversation, 5 interleaved cold/warm pairs ----------------
print("    --- LEG G: growing conversation, cold twin per turn, interleaved ---")
GB = ABAKE * 3
UF = ["Now expand point %d of that summary and explain the trade-offs in detail." % i
      for i in range(1, 12)]
def grow(turn, nonce=""):
    msgs = [{"role": "user", "content": nonce + U1}]
    for k in range(2, turn + 1):
        msgs.append({"role": "assistant", "content": GB})
        msgs.append({"role": "user", "content": UF[k - 2]})
    return msgs
if SKIP_FG:
    print("    LEG G SKIPPED (GS_LEGS=S): the deeper turns' cold walk primes exceed the "
          "90 s first-token deadline")
else:
    send("g-warm", "t1", grow(1), "gsG-%s" % name)
    for k in range(2, 7):
        send("g-cold", "t%d" % k, grow(k, nonce="[grow %s c%02d] " % (name, k)),
             "gsGC-%s-%02d" % (name, k))
        send("g-warm", "t%d" % k, grow(k), "gsG-%s" % name)

# ---------------- verdicts ----------------
print("    delta keys observed on the wire: %s" % (FIRST_KEYS[0] if FIRST_KEYS else "NONE SEEN"))
EMPTY = hashlib.sha256(b"").hexdigest()[:16]
valid = [r for r in rows if r["sha"] and r["ttft"] is not None and not r["err"]]
print("    valid_rows=%d/%d (empties rejected in the instrument; sha256('')=%s)"
      % (len(valid), len(rows), EMPTY))
if not valid:
    print("    ARM INVALID: no valid rows"); raise SystemExit(0)

print("    --- LEG S VERDICT ---")
npass = nfail = ninv = 0
for key, target, nw, w, c in ident:
    if not (w["sha"] and c["sha"]) or w["err"] or c["err"]:
        print("      %s INVALID (empty or errored row)" % key); ninv += 1; continue
    if not w["rewound"]:
        print("      %s INVALID (warm row did not rewind: it was not a suffix prime)" % key)
        ninv += 1; continue
    if c["rewound"]:
        print("      %s INVALID (cold twin rewound: it was not a full prime)" % key)
        ninv += 1; continue
    ok = w["sha"] == c["sha"]
    npass += ok; nfail += (not ok)
    print("      %s suffix=%s tokens target=%d filler=%d | warm sha=%s chars=%d | "
          "cold sha=%s chars=%d -> %s"
          % (key, w["suffix"], target, nw, w["sha"], w["chars"], c["sha"], c["chars"],
             "MATCH" if ok else "DIFFER"))
print("      LEG S: pass=%d fail=%d invalid=%d" % (npass, nfail, ninv))
shas = [w["sha"] for _, _, _, w, _ in ident if w["sha"]]
print("      collision check: %d distinct completions over %d swept prompts (max_tokens=%d)"
      % (len(set(shas)), len(shas), MAXTOK))

def stats(v):
    if not v: return "n=0"
    s = sorted(v); m = s[len(s)//2] if len(s) % 2 else (s[len(s)//2-1]+s[len(s)//2])/2
    return "n=%d median=%.3f min=%.3f max=%.3f spread=%.3f" % (len(s), m, s[0], s[-1], s[-1]-s[0])

by = {(r["tag"], r["key"]): r for r in valid}
print("    --- LEG G PAIRWISE TTFT (cold twin vs warm, same turn) ---")
wins, ratios = [], []
for k in range(2, 7):
    c, w = by.get(("g-cold", "t%d" % k)), by.get(("g-warm", "t%d" % k))
    if not c or not w: continue
    print("      t%d cold=%.3f warm=%.3f delta=%+.3fs ratio=%.3fx warm_rewound=%s "
          "warm_eng_suffix=%d warm_walk_suffix=%d"
          % (k, c["ttft"], w["ttft"], c["ttft"]-w["ttft"], c["ttft"]/w["ttft"], w["rewound"],
             w["eng_suffix"], w["walk_suffix"]))
    wins.append(c["ttft"] - w["ttft"]); ratios.append(c["ttft"] / w["ttft"])
print("    pairwise TTFT win seconds: %s" % stats(wins))
print("    pairwise TTFT ratio      : %s" % stats(ratios))

# SUFFIX COST LINE, this arm. The coordinator's five-point sweep measured the WALK suffix at
# ttft = 0.2529 s + 5.5978 ms/suffix-token (R^2 0.9976) against a cold chunked prime of
# 0.99 ms/token. The whole claim of this lane is that the slope collapses to the cold rate
# when the suffix rides the batched entry, so fit the same line here, per arm, from LEG S's
# own warm rows -- same instrument, same cell, directly comparable slopes.
def lsq(xs, ys):
    n = len(xs)
    if n < 3: return None
    mx = sum(xs) / n; my = sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    if sxx == 0: return None
    b = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx
    a = my - b * mx
    ss_res = sum((y - (a + b * x)) ** 2 for x, y in zip(xs, ys))
    ss_tot = sum((y - my) ** 2 for y in ys)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else float("nan")
    return a, b, r2

sx = [(w["suffix"], w["ttft"]) for _, _, _, w, _ in ident
      if w["suffix"] and w["ttft"] is not None and w["sha"] and w["rewound"]]
print("    --- SUFFIX COST LINE (LEG S warm rows, this arm) ---")
for L, t in sx:
    print("      suffix=%-5d ttft=%.3f" % (L, t))
f = lsq([L for L, _ in sx], [t for _, t in sx])
if f:
    a, b, r2 = f
    print("      LEAST SQUARES: ttft = %.4f s + %.4f ms/suffix-token, R^2 = %.4f  (n=%d)"
          % (a, b * 1000.0, r2, len(sx)))
    print("      REFERENCE (coordinator sweep, walk suffix): 0.2529 s + 5.5978 ms/token; "
          "cold chunked prime 0.99 ms/token")
    print("      slope vs walk = %.2fx   slope vs cold prime = %.2fx"
          % (b * 1000.0 / 5.5978, b * 1000.0 / 0.99))
else:
    print("      LEAST SQUARES: not enough valid rewound rows to fit (n=%d)" % len(sx))

print("    --- ENGAGEMENT TOTALS (both directions) ---")
tot = {kf: sum(r[kf] for r in rows) for kf in
       ("eng_fresh", "eng_suffix", "walk_fresh", "walk_suffix")}
for kf in ("eng_fresh", "eng_suffix", "walk_fresh", "walk_suffix"):
    print("      %-12s = %d" % (kf, tot[kf]))
# ARM VALIDITY, not just row validity. An arm whose fast prime never armed compares walk to
# walk and proves nothing; an arm claiming the suffix path with zero suffix engagements is the
# receipt defect this lane has already been bitten by twice, in both directions.
want_suffix = os.environ.get("EXPECT_SUFFIX_ARM", "1") == "1"
want_fresh_eng = os.environ.get("EXPECT_FRESH_ENG", "1") == "1"
checks = []
if want_fresh_eng:
    checks.append(("fast prime armed at all (eng_fresh>0)", tot["eng_fresh"] > 0))
else:
    # WALK-ONLY arm (MEMRA_STEP_GEMM_PRIME=0): the batched prime must be absent entirely.
    checks.append(("batched prime fully off (eng_fresh==0 and eng_suffix==0)",
                   tot["eng_fresh"] == 0 and tot["eng_suffix"] == 0))
    checks.append(("everything took the walk (walk_fresh>0 and walk_suffix>0)",
                   tot["walk_fresh"] > 0 and tot["walk_suffix"] > 0))
if want_fresh_eng:
    if want_suffix:
        checks += [("suffix rode the batched prime (eng_suffix>0)", tot["eng_suffix"] > 0),
                   ("no suffix fell through to the walk (walk_suffix==0)", tot["walk_suffix"] == 0)]
    else:
        checks += [("no suffix rode the batched prime (eng_suffix==0)", tot["eng_suffix"] == 0),
                   ("suffixes took the walk (walk_suffix>0)", tot["walk_suffix"] > 0)]
bad = [c for c, ok in checks if not ok]
for c, ok in checks:
    print("      ARM CHECK %-52s %s" % (c, "OK" if ok else "FAIL"))
print("      ARM VALIDITY: %s" % ("VALID" if not bad else "INVALID -- " + "; ".join(bad)))
if legf:
    print("    --- LEG F: fresh sha=%s chars=%s prompt_tokens=%s (compare across arms) ---"
          % (legf["sha"], legf["chars"], legf.get("prompt_tokens")))
print("    CROSSARM " + json.dumps({"%s/%s" % (r["tag"], r["key"]):
                                    [r["sha"], r["chars"], r["rewound"], r["suffix"]]
                                    for r in rows}))
