#!/bin/bash
# step37 vision e2e server boot (lane/step37-vision-20260830).
# ENVV = the box smoke recipe MINUS the removed v2-bank doors (MEMRA_NVFP4_BANK_V2,
# MEMRA_SEL_DOWN8 were deleted in fd0a175ab and refuse in serving since 75bf4ce76).
set -u
MODE=${1:-vision}   # vision | plain
PORT=${2:-18902}
BIN=/home/ubuntu/wt-step37-vision/target/release/memra-server
LOG=/home/ubuntu/step37-vision-lane/server-$MODE.log
ENVV="MEMRA_OPROJ_TAIL=1 MEMRA_DEV1_ROUTER=1 MEMRA_LEN_MIRROR_LAZY=1 MEMRA_ASYNC_CHAIN=8 MEMRA_SHEXP_OVERLAP=1 MEMRA_ROUTES_PRESTAGE=1 MEMRA_MOE_DIRECT=1 MEMRA_OPROJ_DIRECT=1 MEMRA_STEP_TP=0-44@0,1 MEMRA_STEP_TP_NATIVE_P2P=1 MEMRA_STEP_NVFP4_DEV_ROUTES=1 MEMRA_STEP_TP_DECODE_V2=1 MEMRA_STEP_TP_QKV_FUSED=1 MEMRA_BF16_MMV=1 MEMRA_STEP_TP_DEV_ROUTER=1 MEMRA_STEP_TP_DCW=1 MEMRA_RMS_BLOCK=1024 MEMRA_SIG_EXPF_DEV=1 MEMRA_HEAD_SPLIT=1 MEMRA_FA_DCW_MEMSET=0 MEMRA_NO_LOCAL_SHADOW=1 MEMRA_FUSE_ROPE_APPEND=1 MEMRA_SEL_MIRROR=1 MEMRA_FA_COMBINE_S=1 MEMRA_MAX_CTX=262144"
VIS=""
if [ "$MODE" = "vision" ]; then VIS="MEMRA_STEP_VISION_DIR=/data/models/step37-flash-nvfp4"; fi
env $ENVV $VIS MEMRA_LOAD_MTP=1 MEMRA_MTP_HEADS=3 MEMRA_SPEC_K=3 MEMRA_SPEC_PMIN=0.5 \
  MEMRA_SPEC_PMIN0=1 MEMRA_CTX=262144 MEMRA_SERVE_SPEC=1 \
  MEMRA_MODELS="step37=/data/models/step37-flash-nvfp4" MEMRA_ADDR=127.0.0.1:$PORT \
  nohup $BIN > $LOG 2>&1 &
echo "pid=$!"
