//! Boot-time audit of the `MEMRA_*` names present in the environment (memra #483).
//!
//! A deleted environment name has two endings and only one of them is safe. `MEMRA_DSV4_MOE_PROGRAM=
//! reference` after the matrix flip parsed into nothing and selected nothing; a paired accuracy
//! control then compared matrix against matrix and reported a perfect null. The safe ending is the
//! one `TP_SPEC_O2_BAND` got when it was renamed: a stale caller dies at boot with the new name in
//! the message.
//!
//! The registry is generated by `build.rs` from `docs/FLAGS.md`, the one catalog the flags census
//! (`tools/check-flags.sh`) already forces every runtime read to appear in: every `MEMRA_...` name
//! mentioned outside the `## Removed ...` ledgers is legal (a trailing `*` names a prefix family;
//! this is the census's own acceptance rule, so the audit never refuses a name the census passed),
//! and every door listed under a ledger that no longer has a live row DEFINITION (first table cell)
//! is retired, carrying its ledger heading. Retired outranks legal: a prose wildcard like
//! `MEMRA_DSV4_*` does not resurrect a deleted DSV4 door.
//!
//! Scope, so this does not refuse the whole namespace: launchers legitimately set names no
//! subsystem owns. A name is refused when it is RETIRED, or when it is unknown inside an OWNED
//! family (a `MEMRA_<FAMILY>_` prefix with at least `OWNED_FAMILY_MIN` legal names, the shape the
//! DSV4 registry already enforces for its own prefixes). An unknown name outside every owned family
//! is a warning, printed once, never a refusal.
//!
//! `MEMRA_ENV_AUDIT=0` disables the audit (announced), `=warn` downgrades refusals to warnings.

include!(concat!(env!("OUT_DIR"), "/memra_env_registry.rs"));

/// A family needs this many documented names before an unknown sibling is refused rather than
/// warned about.
pub const OWNED_FAMILY_MIN: usize = 3;

#[derive(Debug, Default, PartialEq, Eq)]
pub struct EnvAudit {
    /// Names that must stop the boot, each with its reason.
    pub refusals: Vec<String>,
    /// Names worth a line but not a refusal.
    pub warnings: Vec<String>,
}

fn family_of(name: &str) -> Option<&str> {
    // `MEMRA_DSV4_FOO` -> `MEMRA_DSV4_`; a two-segment name (`MEMRA_MODELS`) has no family.
    let rest = name.strip_prefix("MEMRA_")?;
    let cut = rest.find('_')?;
    Some(&name[..("MEMRA_".len() + cut + 1)])
}

fn is_legal(name: &str) -> bool {
    LEGAL_NAMES.binary_search(&name).is_ok() || LEGAL_PREFIXES.iter().any(|p| name.starts_with(p))
}

fn retired(name: &str) -> Option<&'static str> {
    RETIRED
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, heading)| *heading)
}

fn family_is_owned(family: &str) -> bool {
    LEGAL_NAMES.iter().filter(|n| n.starts_with(family)).count() >= OWNED_FAMILY_MIN
        || LEGAL_PREFIXES.iter().any(|p| p.starts_with(family))
}

/// Audit an explicit set of `(name, value)` pairs. Pure: tests feed it synthetic environments.
pub fn audit_vars<I, K, V>(vars: I) -> EnvAudit
where
    I: IntoIterator<Item = (K, V)>,
    K: AsRef<str>,
    V: AsRef<str>,
{
    let mut out = EnvAudit::default();
    let mut names: Vec<String> = vars
        .into_iter()
        .map(|(k, _)| k.as_ref().to_string())
        .filter(|k| k.starts_with("MEMRA_"))
        .collect();
    names.sort();
    names.dedup();
    for name in names {
        if name == "MEMRA_ENV_AUDIT" {
            continue;
        }
        // Retired first: a prose wildcard such as `MEMRA_DSV4_*` documents the family, and a
        // deleted door still matches it. The ledger outranks the wildcard.
        if let Some(heading) = retired(&name) {
            out.refusals.push(format!(
                "{name}: retired. See docs/FLAGS.md '{heading}'. The value parses into nothing now; \
                 unset it, and if the arm it selected is the one you need, the ledger names what \
                 replaced it."
            ));
            continue;
        }
        if is_legal(&name) {
            continue;
        }
        match family_of(&name) {
            Some(family) if family_is_owned(family) => {
                let siblings = LEGAL_NAMES.iter().filter(|n| n.starts_with(family)).count();
                out.refusals.push(format!(
                    "{name}: unknown {family}* name ({siblings} documented names in that family, \
                     none is this one). Not in docs/FLAGS.md and not in its Removed ledgers: a typo \
                     or a name from another tree. It would be read by nothing."
                ));
            }
            _ => out.warnings.push(format!(
                "{name}: not a documented memra name (docs/FLAGS.md); nothing in this process \
                 reads it. Left alone: launchers own names outside the engine's families."
            )),
        }
    }
    out
}

/// How `MEMRA_ENV_AUDIT` shapes the boot decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditMode {
    Refuse,
    Warn,
    Off,
}

pub fn audit_mode() -> AuditMode {
    match std::env::var("MEMRA_ENV_AUDIT").as_deref() {
        Ok("0") | Ok("off") => AuditMode::Off,
        Ok("warn") => AuditMode::Warn,
        _ => AuditMode::Refuse,
    }
}

/// Audit the live process environment. `Err` carries the refusal text a boot must print and die
/// with; warnings are printed here. Under `MEMRA_ENV_AUDIT=0` the audit announces itself off and
/// returns `Ok`; under `=warn` refusals print as warnings and the boot continues.
pub fn audit_process_env() -> Result<(), String> {
    let mode = audit_mode();
    if mode == AuditMode::Off {
        eprintln!(
            "[env-audit] MEMRA_ENV_AUDIT=0: the MEMRA_* environment audit is OFF for this boot"
        );
        return Ok(());
    }
    let audit = audit_vars(std::env::vars());
    for w in &audit.warnings {
        eprintln!("[env-audit] warning: {w}");
    }
    if audit.refusals.is_empty() {
        return Ok(());
    }
    if mode == AuditMode::Warn {
        for r in &audit.refusals {
            eprintln!("[env-audit] warning (MEMRA_ENV_AUDIT=warn downgraded a refusal): {r}");
        }
        return Ok(());
    }
    let mut msg = String::from(
        "[env-audit] REFUSED: the environment names doors this build does not have:\n",
    );
    for r in &audit.refusals {
        msg.push_str("  ");
        msg.push_str(r);
        msg.push('\n');
    }
    msg.push_str(
        "  Unset them (or MEMRA_ENV_AUDIT=warn for one boot while the launcher is fixed). \
         Registry: docs/FLAGS.md, generated into this binary at build time.",
    );
    Err(msg)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn audit(pairs: &[(&str, &str)]) -> EnvAudit {
        audit_vars(pairs.iter().map(|(k, v)| (*k, *v)))
    }

    #[test]
    fn registry_is_populated_sorted_and_disjoint() {
        assert!(LEGAL_NAMES.len() > 200, "{} legal names", LEGAL_NAMES.len());
        assert!(!RETIRED.is_empty());
        assert!(
            LEGAL_NAMES.windows(2).all(|w| w[0] < w[1]),
            "LEGAL_NAMES must be sorted for binary_search"
        );
        for (name, heading) in RETIRED {
            assert!(
                LEGAL_NAMES.binary_search(name).is_err(),
                "{name} is both a legal name and retired ({heading})"
            );
            assert!(
                heading.starts_with("Removed"),
                "{name}: heading {heading:?}"
            );
        }
    }

    /// Non-vacuity: every legal name exported at once refuses nothing and warns about nothing.
    #[test]
    fn every_legal_name_passes() {
        let pairs: Vec<(&str, &str)> = LEGAL_NAMES.iter().map(|n| (*n, "1")).collect();
        let a = audit(&pairs);
        assert!(a.refusals.is_empty(), "{:?}", a.refusals);
        assert!(a.warnings.is_empty(), "{:?}", a.warnings);
        // prefix families admit any suffix
        if let Some(p) = LEGAL_PREFIXES.first() {
            let name = format!("{p}ANY_SUFFIX");
            let a = audit(&[(name.as_str(), "1")]);
            assert!(a.refusals.is_empty() && a.warnings.is_empty(), "{a:?}");
        }
    }

    /// Red arm: a retired door refuses and names its ledger.
    #[test]
    fn a_retired_door_refuses_with_its_ledger() {
        let (name, heading) = RETIRED[0];
        let a = audit(&[(name, "reference")]);
        assert_eq!(a.refusals.len(), 1, "{a:?}");
        assert!(
            a.refusals[0].contains(name) && a.refusals[0].contains(heading),
            "{}",
            a.refusals[0]
        );
        assert!(a.warnings.is_empty());
        // the incident's own name, when it is in the ledger
        if RETIRED.iter().any(|(n, _)| *n == "MEMRA_DSV4_MOE_PROGRAM") {
            let a = audit(&[("MEMRA_DSV4_MOE_PROGRAM", "reference")]);
            assert_eq!(a.refusals.len(), 1);
        }
    }

    /// An unknown name inside an owned family refuses; outside every family it only warns.
    #[test]
    fn unknown_names_refuse_inside_owned_families_and_warn_outside() {
        let family = LEGAL_NAMES
            .iter()
            .filter_map(|n| family_of(n))
            .find(|f| family_is_owned(f))
            .expect("at least one owned family");
        let inside = format!("{family}DEFINITELY_NOT_A_DOOR_ZZ");
        let a = audit(&[(inside.as_str(), "1")]);
        assert_eq!(a.refusals.len(), 1, "{a:?}");
        assert!(a.refusals[0].contains("unknown"), "{}", a.refusals[0]);
        let a = audit(&[("MEMRA_ZZ_ORPHAN_LAUNCHER_ONLY", "1")]);
        assert!(a.refusals.is_empty(), "{a:?}");
        assert_eq!(a.warnings.len(), 1);
        // the audit's own switch and non-MEMRA names are ignored
        let a = audit(&[("MEMRA_ENV_AUDIT", "warn"), ("PATH", "/bin")]);
        assert_eq!(a, EnvAudit::default());
    }
}
