#!/usr/bin/env bash
# Constrained-decoding battery (lane/constrained, 2026-08-03).
#   Phase A — NO-OP EXACTNESS: unconstrained requests against the BASELINE binary
#             (pre-lane, /tmp/memra-server-baseline) vs the NEW binary must be
#             byte-identical (greedy + seeded-sampled).
#   Phase B — CONSTRAINED CORRECTNESS: json_object output parses as JSON;
#             json_schema output parses AND validates against the schema (python jsonschema).
#   Phase C — MASK COST: same session, N=3 constrained vs N=3 unconstrained tok/s,
#             + the worker's [constrained] ms/step lines from the log.
# GPU serialized via flock /tmp/gpu5090.lock (shared rig).
set -uo pipefail
cd "$(dirname "$0")/../.."

MODEL=/data/ai-ml/hf-models/qwen35-9b-nvfp4-gguf/Qwen3.5-9B-NVFP4-MTP-GGUF.gguf
ADDR=127.0.0.1:8191
BASE=http://$ADDR
OUT=research/constrained-20260803
FAILS=0
PASS() { echo "  ok: $1"; }
FAIL() { echo "  FAIL: $1"; FAILS=$((FAILS+1)); }

start_server() { # $1 = binary path, $2 = log file
  MEMRA_COMPAT=openai MEMRA_MODELS="q9=$MODEL" MEMRA_ADDR=$ADDR "$1" > "$2" 2>&1 &
  SPID=$!
  for _ in $(seq 150); do curl -sf $BASE/health >/dev/null 2>&1 && return 0; sleep 2; done
  echo "server did not come up; log tail:"; tail -5 "$2"; return 1
}
stop_server() { kill "${SPID:-0}" 2>/dev/null; wait "${SPID:-0}" 2>/dev/null || true; }
trap stop_server EXIT

req() { # $1=prompt $2=max_tokens $3=temperature $4=seed $5=extra-json ("" for none)
  local extra=""
  [ -n "$5" ] && extra=",$5"
  curl -sf -m 300 $BASE/v1/chat/completions -H 'Content-Type: application/json' \
    -d "{\"model\":\"q9\",\"messages\":[{\"role\":\"user\",\"content\":\"$1\"}],\
\"max_tokens\":$2,\"temperature\":$3,\"seed\":$4$extra}"
}

content() { python3 -c 'import sys,json; print(json.load(sys.stdin)["choices"][0]["message"]["content"], end="")'; }
# The FULL generated byte stream (reasoning + content + token count) — the exactness
# comparator. content-only would compare empty-vs-empty when a small budget ends inside
# the think segment.
fullmsg() { python3 -c '
import sys,json
r=json.load(sys.stdin); m=r["choices"][0]["message"]
print(json.dumps({"reasoning": m.get("reasoning"), "content": m["content"],
                  "n": r["usage"]["completion_tokens"]}, sort_keys=True))'; }

# ---------- Phase A: no-op exactness (baseline vs new, unconstrained) ----------
echo "== Phase A: unconstrained byte-identity (baseline vs lane binary) =="
PROMPTS=("Explain PCIe lanes in two sentences." "List three prime numbers." "What is a mutex?")
for side in baseline new; do
  BIN=$([ $side = baseline ] && echo /tmp/memra-server-baseline || echo target/release/memra-server)
  start_server "$BIN" "/tmp/constrained-$side.log" || exit 1
  for i in 0 1 2; do
    req "${PROMPTS[$i]}" 96 0 0 ""            | fullmsg > "$OUT/exact-$side-greedy-$i.txt"
    req "${PROMPTS[$i]}" 96 0.8 42 ""         | fullmsg > "$OUT/exact-$side-temp-$i.txt"
  done
  stop_server
done
for i in 0 1 2; do
  for kind in greedy temp; do
    if cmp -s "$OUT/exact-baseline-$kind-$i.txt" "$OUT/exact-new-$kind-$i.txt"; then
      PASS "unconstrained $kind #$i byte-identical"
    else
      FAIL "unconstrained $kind #$i DIFFERS (mask path not a no-op)"
    fi
  done
done

# ---------- Phase B + C on the new binary ----------
start_server target/release/memra-server /tmp/constrained-lane.log || exit 1

echo "== Phase B: constrained correctness =="
# json_object: output must parse as a JSON object. Budget must cover the full object —
# a max_tokens cut mid-string is truncated JSON with finish_reason:"length", the same
# semantics as vLLM/OpenAI (grammars bound the SHAPE, not the length).
req "Describe a dog as a small JSON object with three keys." 512 0 0 \
  '"response_format":{"type":"json_object"}' \
  | content > "$OUT/json-object-out.txt"
if python3 -c '
import json,sys
v=json.load(open(sys.argv[1]))
assert isinstance(v,dict), f"not an object: {type(v)}"
' "$OUT/json-object-out.txt"; then PASS "json_object parses as object"; else
  FAIL "json_object output invalid: $(head -c 200 "$OUT/json-object-out.txt")"; fi

# json_schema: output must parse AND validate.
SCHEMA='{"type":"object","properties":{"name":{"type":"string"},"age":{"type":"integer","minimum":0},"tags":{"type":"array","items":{"type":"string"},"minItems":2}},"required":["name","age","tags"],"additionalProperties":false}'
req "Invent a person named Rex, age 7, with hobby tags. Reply as JSON." 220 0 0 \
  "\"response_format\":{\"type\":\"json_schema\",\"json_schema\":{\"name\":\"person\",\"schema\":$SCHEMA}}" \
  | content > "$OUT/json-schema-out.txt"
if python3 -c "
import json,sys,jsonschema
v=json.load(open(sys.argv[1]))
jsonschema.validate(v, json.loads('$SCHEMA'))
" "$OUT/json-schema-out.txt"; then PASS "json_schema parses AND validates"; else
  FAIL "json_schema output invalid: $(head -c 200 "$OUT/json-schema-out.txt")"; fi

# sampled constrained (temp>0): still must validate.
req "Invent a person. Reply as JSON." 220 0.8 7 \
  "\"response_format\":{\"type\":\"json_schema\",\"json_schema\":{\"name\":\"person\",\"schema\":$SCHEMA}}" \
  | content > "$OUT/json-schema-sampled-out.txt"
if python3 -c "
import json,sys,jsonschema
v=json.load(open(sys.argv[1]))
jsonschema.validate(v, json.loads('$SCHEMA'))
" "$OUT/json-schema-sampled-out.txt"; then PASS "sampled json_schema validates"; else
  FAIL "sampled json_schema invalid: $(head -c 200 "$OUT/json-schema-sampled-out.txt")"; fi

# bad schema type: loud 400.
CODE=$(curl -s -o /dev/null -w '%{http_code}' -m 60 $BASE/v1/chat/completions \
  -H 'Content-Type: application/json' \
  -d '{"model":"q9","messages":[{"role":"user","content":"x"}],"response_format":{"type":"yaml"}}')
[ "$CODE" = 400 ] && PASS "unknown response_format type is a 400" \
                  || FAIL "unknown response_format type gave $CODE (want 400)"

echo "== Phase C: mask cost (N=3 each, same session) =="
perf_row() { # $1=label $2=extra-json
  local t0 t1 n toks
  for k in 1 2 3; do
    t0=$(date +%s.%N)
    resp=$(req "Write a long JSON object describing a spacecraft with at least ten keys." 256 0 0 "$2")
    t1=$(date +%s.%N)
    n=$(echo "$resp" | python3 -c 'import sys,json; print(json.load(sys.stdin)["usage"]["completion_tokens"])')
    python3 -c "print(f'$1 run$k: {$n} tok in {$t1-$t0:.2f}s = {$n/($t1-$t0):.1f} tok/s')"
  done
}
perf_row "unconstrained" ""
perf_row "constrained  " '"response_format":{"type":"json_object"}'
grep '\[constrained\]' /tmp/constrained-lane.log | tail -8

stop_server
cp /tmp/constrained-lane.log "$OUT/serve-lane.log"
echo; echo "battery: $FAILS failure(s)"
exit $((FAILS > 0))
